### ISSUE TITLE
Build the Cython modules Error

### ISSUE THREAD

**Issue by lbin** [yuxng/SubCNN#1]
When I built the Cython modules, I got this error:

> postargs = extra_compile_args['gcc']
> TypeError: list indices must be integers, not str

So how to fix this?
Thank you very much.

**Comment by zeroAska** [comment]
Also had this problem. How to fix it? Thanks!

**Comment by yuxng** [comment]
Fix it. Please do a git pull to get the new setup.py under fast-rcnn/lib

**Comment by lbin** [comment]
@yuxng Thank you
