### ISSUE TITLE
How much memory does detection exactly need???12G not enough?

### ISSUE THREAD

**Issue by litingfeng** [yuxng/SubCNN#10]
when I run 

` ./experiments/scripts/kitti_val_caffenet_rcnn_multiscale.sh 0 `

I got 
`Check failed: error == cudaSuccess (2 vs. 0)  out of memory
`
Then I changed syncedmem.cpp to see how much size it needs, the result is 

`I0718 16:01:56.864768  7131 syncedmem.cpp:51] Malloc on gpu, size=: 1430784000
I0718 16:01:56.865655  7131 syncedmem.cpp:51] Malloc on gpu, size=: 676269000
I0718 16:01:56.920502  7131 syncedmem.cpp:51] Malloc on gpu, size=: 359227392
I0718 16:01:56.920802  7131 syncedmem.cpp:51] Malloc on gpu, size=: 359227392
I0718 16:01:56.921123  7131 syncedmem.cpp:51] Malloc on gpu, size=: 359227392
I0718 16:01:56.921419  7131 syncedmem.cpp:51] Malloc on gpu, size=: 359227392
I0718 16:01:57.313796  7131 syncedmem.cpp:51] Malloc on gpu, size=: 957939712
I0718 16:01:57.314327  7131 syncedmem.cpp:51] Malloc on gpu, size=: 1122585600
I0718 16:01:57.357914  7131 syncedmem.cpp:51] Malloc on gpu, size=: 242810880
I0718 16:01:57.358178  7131 syncedmem.cpp:51] Malloc on gpu, size=: 242810880
I0718 16:01:57.358423  7131 syncedmem.cpp:51] Malloc on gpu, size=: 242810880`

....

This shows size in each layer, I added them up, the results > 10G.

I have two Tesla k40, each has 12G memory, isn't that enough?

**Comment by zeroAska** [comment]
I have the same issue here. What batch size are you using?

**Comment by litingfeng** [comment]
@zeroAska I changed TRAIN.BATCH_SIZE and TRAIN.RPN_BATCHSIZE into 2, but still out of memory. I notice that the memory required did not change,  I dont know whether this is the reason

**Comment by yuxng** [comment]
I am using Titan X with 12G, and it works for me.

**Comment by litingfeng** [comment]
@zeroAska  hi, have you solved this problem? i tried on titan, but it was still out of memory

**Comment by litingfeng** [comment]
@yuxng I tried to use Titan X with 12G, but it still ran out of memory. I don't know why.

**Comment by yuxng** [comment]
Try to use cudnn. The convolution in cudnn uses less memory.

**Comment by litingfeng** [comment]
@yuxng  I always use this，but  it doesn't fix this problem

**Comment by yuxng** [comment]
If it still does not work, try to change the scale parameter in the yml configure file smaller.

**Comment by litingfeng** [comment]
@yuxng  I changed like this
 SCALES_BASE: !!python/tuple [1.0, 2.0, 3.0]     

but encountered this problem
` error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered`

Thank you for your patience!

**Comment by litingfeng** [comment]
@yuxng sorry, I forgot something, I also changed the 18th line to 
NUM_PER_OCTAVE: 3
 
is there anything else needed change?

**Comment by zeroAska** [comment]
@litingfeng Have you tried to make scale even smaller, like [1.0, 2.0]?

**Comment by litingfeng** [comment]
@zeroAska dude , you saved me.
