### ISSUE TITLE
what is the format of the /voxel_exemplars/test/007480.txt?

### ISSUE THREAD

**Issue by zhoutengteng** [yuxng/SubCNN#13]
in   /voxel_exemplars/test/007480.txt 
Car -1 0 0.00 185.93 214.05 348.86
Car 226 0 57.68 178.66 341.72 285.91
Car 130 0 133.20 154.23 386.37 263.44
Car -1 0 1094.88 190.09 1241.00 374.00
Car -1 0 934.82 184.38 1241.00 326.25
Car 143 0 882.79 183.25 1122.39 291.95
Car 197 0 800.16 181.42 1050.12 273.59
Car 129 0 755.13 184.19 967.47 253.54
Car 143 0 749.78 170.88 917.51 243.48
Car 131 0 344.07 180.05 479.10 224.15
Car 180 0 382.70 179.71 495.48 219.10
Car 85 0 631.71 179.85 678.40 214.37
Car -1 0 619.92 176.90 647.01 199.92
Car -1 1 1028.95 185.93 1243.00 348.86
Car 227 1 901.28 178.66 1185.32 285.91
Car 197 1 856.63 154.23 1109.80 263.44
Car -1 1 2.00 190.09 148.12 374.00
Car -1 1 2.00 184.38 308.18 326.25
Car 128 1 120.61 183.25 360.21 291.95
Car 130 1 192.88 181.42 442.84 273.59
Car 128 1 275.53 184.19 487.87 253.54
Car 186 1 325.49 170.88 493.22 243.48
Car 24 1 763.90 180.05 898.93 224.15
Car 196 1 747.52 179.71 860.30 219.10
Car 127 1 564.60 179.85 611.29 214.37
Car -1 1 595.99 176.90 623.08 199.92
Cyclist 268 0 501.01 178.40 523.53 228.03
Cyclist 269 1 719.47 178.40 741.99 228.03

how can I understand the format of the data？Thanks

**Comment by yuxng** [comment]
The format of this file is
class name, subcategory index (-1 indicates that the example is not used), a flag for flipping (1 indicates that the example is flipped in the image from left to right), x1, y1, x2, y2 (bounding box coordinates)

**Comment by litingfeng** [comment]
@yuxng I noticed that some of these boxes in this file(voxel_exemplars) are not correct, since I saw some are bounding background but labeled with "Car". I don't understand why. Thank you

**Comment by yuxng** [comment]
This is due to the errors in the kitti ground truth annotations.
