### ISSUE TITLE
what is the format of the /voxel_exemplars/test/mapping.txt?

### ISSUE THREAD

**Issue by zhoutengteng** [yuxng/SubCNN#15]
1 Car 220.152672 -0.870000
2 Car 139.847328 -2.271593
3 Car 165.148723 -1.830000
4 Car 75.584803 2.890000
5 Car 284.415197 0.251593
6 Car 173.078880 -1.691593
7 Car 11.986488 1.780000

Thanks

Additional， What is the purpose of using mapping txt？   Because there has been image folder and image_label folder.

**Comment by yuxng** [comment]
The mapping file stores information from subcategory to category and viewpoint. The format of the file is "subclass index, category name, azimuth, alpha in kitti format".

**Comment by leonliuzju** [comment]
Is there any code for get the map file? I'd like to get the subcategory for my own dataset.

**Comment by leonliuzju** [comment]
I've got it .. For 2D subcategory, you use the objects orientation as feature, and then use affinity propagation clustering algorithm to get subcategory. That can proves the more information the higher accuracy, but did you test that only using the information of bbox to get subcategory, dose it help?
Besides, the Pascal VOC dataset doesn't give the orientation, how do you get subcategory?

**Comment by yuxng** [comment]
You can do 2D clustering with image features if there is no orientation information.
