### ISSUE TITLE
ERROR  in kitti_val_caffenet_rcnn_multiscale.sh

### ISSUE THREAD

**Issue by litingfeng** [yuxng/SubCNN#17]
I ran this file, when it came to `time ./tools/test_net.py --gpu $1 \`, some errors occurred:

`Traceback (most recent call last):
  File "./tools/test_net.py", line 81, in <module>
    test_net(net, imdb)`
 ` File "/home/cyn/debug/SubCNN/fast-rcnn/tools/../lib/fast_rcnn/test.py", line 585, in test_net
    roidb = imdb.roidb`
 ` File "/home/cyn/debug/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 74, in roidb
    self._roidb = self.roidb_handler()`
  `File "/home/cyn/debug/SubCNN/fast-rcnn/tools/../lib/datasets/kitti.py", line 465, in region_proposal_roidb`
   ` roidb = datasets.imdb.merge_roidbs(rpn_roidb, gt_roidb)`
`File "/home/cyn/debug/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 321, in merge_roidbs
    b[i]['gt_overlaps']])`
 ` File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 454, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)`
 ` File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 533, in bmat`
   ` raise ValueError('blocks[%d,:] is all None' % brow_lengths.argmin())`
`ValueError: blocks[1,:] is all None`

I printed out `a[i]['gt_subindexes']` and `b[i]['gt_subindexes']` in imdb, both are **NULL**, is this right? 
How can I fix this problem?

**Comment by yuxng** [comment]
Try to update your scipy version to the newest one.

**Comment by litingfeng** [comment]
I updated it but it doesn't work, so finally I made some change,reference [one Exception about scipy.sparse.vstack #8](https://github.com/yuxng/SubCNN/issues/8)
