### ISSUE TITLE
A make error...

### ISSUE THREAD

**Issue by ngmanhei** [yuxng/SubCNN#2]
Hi, I met a make error while deploying SubCNN on my machine:

src/caffe/layers/feature_extrapolating_layer.cpp: In member function ‘virtual void caffe::FeatureExtrapolatingLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/feature_extrapolating_layer.cpp:48:22: error: ‘stod’ is not a member of ‘std’
     scales_base[i] = std::stod(str, &sz);
                      ^
make: *** [.build_release/src/caffe/layers/feature_extrapolating_layer.o] Error 1
make: *** Waiting for unfinished jobs....

would you please show me how to fix it? Thanks~

**Comment by ngmanhei** [comment]
Haha, I've fixed this problem by adding '-std=c++11' to 'CXXFLAGS' in Makefile

**Comment by yuxng** [comment]
Yes, that is the correct solution :)

**Comment by mhsung** [comment]
The other way without using c++11 is to use boost::lexical_cast:

# include <boost/lexical_cast.hpp>
scales_base[i] = boost::lexical_cast<double>(str);
