### ISSUE TITLE
Can the proposals in RPN_125 be directly drawn on images?

### ISSUE THREAD

**Issue by litingfeng** [yuxng/SubCNN#20]
Can we directly use the proposals in RPN_125 on images or is there some other steps before we use them?

Because when I drew these proposals on images, they are far from the correct locations.

**Comment by yuxng** [comment]
You can draw them on images. I think these are something wrong with the proposals you generated.

**Comment by litingfeng** [comment]
@yuxng I followed the readme, which makes me confused
