### ISSUE TITLE
System deployment

### ISSUE THREAD

**Issue by KarelLebeda** [yuxng/SubCNN#22]
I would like to use the whole system as a car detector in my pipeline, the best would be if I got also some information about the 3D pose (out-of-plane rotation). I guess I would prefer training on the KITTI dataset. How can I use it in the fashion where I give it an image (or a bunch of) and get the detections?

I have started running the experiments on KITTI, went through the first training (took days), how can I use the trained network now? Is there a simple demo script?

Many thanks!

**Comment by yuxng** [comment]
Hi Karel, please check the SubCNN/fast-rcnn/lib/fast_rcnn/test.py file for the test code.
