### ISSUE TITLE
Out of memory during subcategory-aware detection network for validation

### ISSUE THREAD

**Issue by peyush** [yuxng/SubCNN#25]
Hi,
I'm running the detection network for validation (kitti_val_caffenet_rcnn_multiscale.sh). No prior process is running on the card.

Card Specs :K40m 12GB

Will any change in the parameters help ? Thanks in advance.

Details:
I0816 18:38:55.680439 43715 net.cpp:217] Network initialization done.
I0816 18:38:55.680444 43715 net.cpp:218] Memory required for data: 1715928
I0816 18:38:55.680629 43715 solver.cpp:42] Solver scaffolding done.
Loading pretrained model weights from data/imagenet_models/CaffeNet.v2.caffemodel
Solving...
/home/peyush.s/DeepLearning/SubCNN/fast-rcnn/tools/../lib/roi_data_layer/minibatch.py:171: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  labels[fg_rois_per_this_image:] = 0
/home/peyush.s/DeepLearning/SubCNN/fast-rcnn/tools/../lib/roi_data_layer/minibatch.py:175: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  sublabels[fg_rois_per_this_image:] = 0
/home/peyush.s/DeepLearning/SubCNN/fast-rcnn/tools/../lib/roi_data_layer/minibatch.py:298: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
/home/peyush.s/DeepLearning/SubCNN/fast-rcnn/tools/../lib/roi_data_layer/minibatch.py:299: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  bbox_loss_weights[ind, start:end] = [1., 1., 1., 1.]
F0816 18:38:59.410197 43715 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
 **# Check failure stack trace:** 
./experiments/scripts/kitti_val_caffenet_rcnn_multiscale.sh: line 16: 43715 Aborted                 (core dumped) ./tools/train_net.py --gpu $1 --solver models/CaffeNet/kitti_val/solver_rcnn_multiscale.prototxt --weights data/imagenet_models/CaffeNet.v2.caffemodel --imdb kitti_train --cfg experiments/cfgs/kitti_rcnn_multiscale.yml

**Comment by crodriguezo** [comment]
Same problem here

**Comment by wangjuenew** [comment]
I also meet this problem, how could we solve it?@yuxng

**Comment by crodriguezo** [comment]
me too, any suggestion?

**Comment by litingfeng** [comment]
change your SCALES_BASE in yml and prototxt

**Comment by wangjuenew** [comment]
I have solved after compile caffe with cuDNN, thanks a lot

**Comment by yuxng** [comment]
Right, I used cuDNN 6.5 which saves GPU memory.
