### ISSUE TITLE
Shape mismatch when running kitti_val_caffenet_rpn.sh script

### ISSUE THREAD

**Issue by enkhee0906** [yuxng/SubCNN#26]
Hello,

I downloaded trained models on the KITTI dataset from [ftp://cs.stanford.edu/cs/cvgl/SubCNN_models.zip](url) 
I run the RPN to generate region proposals of KITTI validation set using following script.
```
time ./tools/test_net.py --gpu $1 \
  --def models/CaffeNet/kitti_val/test_rpn.prototxt \
  --net output/kitti/kitti_train/caffenet_fast_rcnn_rpn_kitti_iter_40000.caffemodel \
  --imdb kitti_val \
  --cfg experiments/cfgs/kitti_rpn.yml
```
(same as in ./experiments/scripts/kitti_val_caffenet_rpn.sh )

But when I run, it gives following error:
```
I0824 14:19:30.047848 26583 net.cpp:217] Network initialization done.
I0824 14:19:30.047852 26583 net.cpp:218] Memory required for data: 59189316
F0824 14:19:30.072989 26583 blob.cpp:454] Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
*** Check failure stack trace: ***
```

It seems test_rpn.prototxt and output/kitti/kitti_train/caffenet_fast_rcnn_rpn_kitti_iter_40000.caffemodel are mismatch. Could you help me to solve this problem?

Also, when I train RPN network using ./experiments/scripts/kitti_val_caffenet_rpn.sh script, it takes around 2.31s per iteration, which is very slow on single NVIDIA TITAN X 12GB. What GPU and cuDNN version did you use in your experiment and what is average time per iteration when training both RPN and detection network?

**Comment by litingfeng** [comment]
The first time I run RPN on an image it took around 1s+, but the second time I git a new SubCNN then it would take 4s+ per image. I dont know why. Is there any posibility that different  Makefile.config results in this ?

**Comment by litingfeng** [comment]
I encountered the same error that is mismatch, hope somebody can save us

**Comment by yuxng** [comment]
The RPN model on KITTI validation set was broken. I have fixed the problem. Please download the models again from ftp://cs.stanford.edu/cs/cvgl/SubCNN_models.zip. Check this script for usage of these trained models: https://github.com/yuxng/SubCNN/blob/master/fast-rcnn/experiments/scripts/test_subcnn_models.sh
Git pull to get this script

**Comment by chenzhi1992** [comment]
I download the models again and used the test_subcnn_model.sh, but I also had the same error .

**Comment by yuxng** [comment]
I have tested all the models, and it worked fine to me before.
