### ISSUE TITLE
Error in network instantiation 

### ISSUE THREAD

**Issue by djingming** [yuxng/SubCNN#29]
Hi Yu,

I am trying to use your code on PASCAL3D+ dataset. I have followed your instruction, but got the following error when running the following command:

```
./experiments/scripts/pascal3d_vgg16_rpn_6k8k.sh 0
```

I1004 14:59:31.982833 30059 layer_factory.hpp:74] Creating layer data
F1004 14:59:31.982851 30059 layer_factory.hpp:77] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, Concat, ContrastiveLoss, Convolution, Data, Deconvolution, Dropout, DummyData, Eltwise, EuclideanLoss, Exp, FeatureExtrapolating, Flatten, HDF5Data, HDF5Output, HeatmapGenerating, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, LRN, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Pooling, Power, ROIGenerating, ROIPooling, ReLU, Reshape, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, SmoothL1Loss, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, WindowData)
*** Check failure stack trace: ***
./experiments/scripts/pascal3d_vgg16_rpn_6k8k.sh: line 17: 30059 Aborted                 (core dumped) ./tools/train_net.py --gpu $1 --solver models/VGG16/pascal3d/solver_rpn_6k8k.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb pascal3d_train --cfg experiments/cfgs/pascal3d_rpn_vgg16.yml --iters 80000

In fact, I only want to use your trained network to test on our own data set. Since the above does not work, I have also tried to download your models and run

```
./experiments/scripts/test_subcnn_models.sh
```

But that also gives errors in creating the layer. Any idea why this happens?

Thanks

**Comment by yuxng** [comment]
Are you using the caffe inside SubCNN? The error messag

**Comment by yuxng** [comment]
Hello,

Are you using the caffe inside SubCNN? The error message says caffe cannot find the python data layer.

Best,
Yu

**Comment by djingming** [comment]
Yes, I am using the code provided inside caffe-fast-rcnn. I compiled caffe and pycaffe interface. Is it a customized layer?

**Comment by yuxng** [comment]
It is the gt_data_layer in the lib folder. It is a python layer. I am not sure why you cannot use it.

**Comment by djingming** [comment]
Here is how I solved the problem. Instead of just make, I did

```
WITH_PYTHON_LAYER=1 make -j8 && make pycaffe
```

**Comment by yuxng** [comment]
Ah, I see. I set WITH_PYTHON_LAYER := 1 in my Makefile.config.

**Comment by djingming** [comment]
Btw, which cudnn version are you using? I got out of memory issue without using cuDnn, but compile with it generates errors. It seems the cuDnn version issue.

**Comment by yuxng** [comment]
I used cudnn-6.5.
