### ISSUE TITLE
looping when executing kitti_test_caffenet_rpn_msr_6k8k.sh

### ISSUE THREAD

**Issue by zeroAska** [yuxng/SubCNN#3]
Hi,

I'm following the steps of running the **kitti detection dataset**. In **Step 4**, when I wanted to run 
` ./experiments/scripts/kitti_test_caffenet_rpn_msr_6k8k.sh $GPU_ID`, it would loop with the output `Waiting for output/kitti/kitti_trainval/caffenet_fast_rcnn_rpn_msr_6k8k_kitti_iter_80000.caffemodel to exist...`.

So I check the output directory and found that the file `output/kitti/kitti_trainval/caffenet_fast_rcnn_rpn_msr_6k8k_kitti_iter_80000.caffemodel` doesn't exist. The command that trains the `msr_6k8k` model in ` ./experiments/scripts/kitti_test_caffenet_rpn_msr_6k8k.sh` is commented out. Can I just test the model `caffenet_fast_rcnn_rpn_msr_kitti_iter_40000.caffemodel`, which was trained in the last command `./experiments/scripts/kitti_val_caffenet_rpn_msr.sh $GPU_ID`, or do I have to train the 80000 iter model again?

Thanks!

**Comment by yuxng** [comment]
Oh, forgot to uncomment the training command. Yes, you need to first train the model. I changed the script. Please do a git pull
