### ISSUE TITLE
Test your Submodels, I had a new issue

### ISSUE THREAD

**Issue by chenzhi1992** [yuxng/SubCNN#31]
I downloaded your trained models, and tested caffenet_fast_rcnn_rpn_kitti_iter_40000.caffemodel. When I run the RPN to generate region proposals of KITTI validation set using following script.
time ./tools/test_net.py --gpu $1 \
  --def models/CaffeNet/kitti_val/test_rpn.prototxt \
  --net output/kitti/kitti_train/caffenet_fast_rcnn_rpn_kitti_iter_40000.caffemodel \
  --imdb kitti_val \
  --cfg experiments/cfgs/kitti_rpn.yml

when I tested the NO.26 image, I had an issue.
 im_detect: 24/3799 2000 object detected 1.100s 0.004s
(26355L, 5L) 0.814943
(26355L, 174L, 1L, 1L)
(2000L, 4L)
im_detect: 25/3799 2000 object detected 1.100s 0.004s
(25067L, 5L) 0.504243
(25067L, 174L, 1L, 1L)
(2000L, 4L)
im_detect: 26/3799 2000 object detected 1.100s 0.004s
(42077L, 5L) 0.476493
F1009 10:45:04.558007 32672 syncedmem.cpp:51] Check failed: error == cudaSuccess
 (2 vs. 0)  out of memory
*** Check failure stack trace: ***
=========================================================
Anyone can help me, thanks!

**Comment by yuxng** [comment]
Are you using cuDNN?

**Comment by chenzhi1992** [comment]
Yes, but my cuda version is cuda7.5, cudnn version is cudnn v3

**Comment by yuxng** [comment]
It is the out of memory issue. How much GPU memory do you have to run the code?

**Comment by chenzhi1992** [comment]
I use gtx980 ti, gpu memory is 8G

**Comment by chenzhi1992** [comment]
I use gtx980 ti， and gpu memory is 6G .

**Comment by yuxng** [comment]
To use the trained models, you need to have a 12G memory GPU.

**Comment by chenzhi1992** [comment]
i know that vgg16 needs 12g gpu,  caffenet needs 12g too ?


发自网易邮箱大师
On 10/09/2016 17:29, Yu Xiang wrote:
To use the trained models, you need to have a 12G memory GPU.

**Comment by yuxng** [comment]
I used image pyramids in SubCNN. It used more memory. Unless you trained your own models by changing the scale parameters, for my trained models, it requires 12G.

**Comment by chenzhi1992** [comment]
Thanks, I see! If I want to train my own models, how can I change the scale parameters of image pyramids?
Is it right that I changed parameters form __C.TRAIN.SCALES_BASE = (0.25, 0.5, 1.0, 2.0, 3.0) to  (0.5, 1.0, 2.0) in the config.py ? I think I am wrong and it can't work.

**Comment by yuxng** [comment]
Change  __C.TRAIN.SCALES_BASE and the following layer in prototxt.

layer {
  name: 'feature'
  type: 'FeatureExtrapolating'
  bottom: 'conv5'
  top: 'conv5_feature'
  feature_extrapolating_param {
    scale_string: "0.25 0.5 1.0 2.0 3.0" => "0.25 0.5 1.0 2.0"
    num_scale_base: 5 => 4
    num_per_octave: 4 
  }
}
