### ISSUE TITLE
Can't run the first kitti script

### ISSUE THREAD

**Issue by zeroAska** [yuxng/SubCNN#4]
Hi,

I met two issues here and can't run the first kitti script `/experiments/scripts/kitti_val_caffenet_rpn.sh`. 

### can't run with cudnn
Which version of cudnn is supported here? I was using cudnn 3 and caffe can compile. But when executing `/experiments/scripts/kitti_val_caffenet_rpn.sh`, I will have a CUDNN_STATUS_NOT_SUPPORTED error like this:

```
...
I0628 17:31:26.975878 20097 net.cpp:217] Network initialization done.
I0628 17:31:26.975883 20097 net.cpp:218] Memory required for data: 16674124
I0628 17:31:26.976016 20097 solver.cpp:42] Solver scaffolding done.
Loading pretrained model weights from data/imagenet_models/CaffeNet.v2.caffemodel
Solving...
F0628 17:31:27.483799 20097 cudnn_conv_layer.cu:85] **Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED**
*** Check failure stack trace: ***
./experiments/scripts/kitti_val_caffenet_rpn.sh: line 17: 20097 Aborted                 (core dumped) ./tools/train_net.py --gpu $1 --solver models/CaffeNet/kitti_val/solver_rpn.prototxt --weights data/imagenet_models/CaffeNet.v2.caffemodel --imdb kitti_train --cfg experiments/cfgs/kitti_rpn.yml --iters 40000
````

My GPU is Quadro M5000M, which has 8G memory and have compute capability > 3.0.

### out of memory error
When I disable cudnn and try to run this script '/experiments/scripts/kitti_val_caffenet_rpn.sh' again, I still fail due to "out of memory". Then in `$ROOT/fast-rcnn//experiments/cfgs/kitti_rpn.yml`, I reduced the BATCH_SIZE to 1, and IMS_PER_BATCH is also 1, but the training process still failed. The output is: 

```...
I0628 17:59:34.930125  2171 net.cpp:218] Memory required for data: 11774236
I0628 17:59:34.930207  2171 solver.cpp:42] Solver scaffolding done.
Loading pretrained model weights from data/imagenet_models/CaffeNet.v2.caffemodel
Solving...
I0628 18:00:06.085770  2171 solver.cpp:189] Iteration 0, loss = 5.15906
I0628 18:00:06.085804  2171 solver.cpp:204]     Train net output #0: loss_bbox = 0 (* 1 = 0 loss)
I0628 18:00:06.085810  2171 solver.cpp:204]     Train net output #1: loss_subcls = 5.15906 (* 1 = 5.15906 loss)
I0628 18:00:06.085816  2171 solver.cpp:464] Iteration 0, lr = 0.001
F0628 18:00:06.088084  2171 syncedmem.cpp:51] **Check failed: error == cudaSuccess (2 vs. 0)  out of memory**
*** Check failure stack trace: ***
./experiments/scripts/kitti_val_caffenet_rpn.sh: line 17:  2171 Aborted                 (core dumped) ./tools/train_net.py --gpu $1 --solver models/CaffeNet/kitti_val/solver_rpn.prototxt --weights data/imagenet_models/CaffeNet.v2.caffemodel --imdb kitti_train --cfg experiments/cfgs/kitti_rpn.yml --iters 40000
```

Thanks!

**Comment by yuxng** [comment]
I am using Titan X that has 12G memory. 8G may not be enough.

**Comment by ngmanhei** [comment]
@yuxng I'm using Tesla K40. I can see there is a intermediate step of this script that needs a little more than 8G of GPU memory. BTW, have you ever tried to modify you code to support the CUDNN_V5? I think if we can use CUDNN_V5, your project would be greatly benefited because it seems that the speed is the short plank.

**Comment by yuxng** [comment]
I did not use cudnn_v5 before. I agree it can be a way to improve the speed.

**Comment by zeroAska** [comment]
@yuxng what version of cudnn are you using?
