### ISSUE TITLE
Kitti Step 5: Copy the region proposals to $ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_*:

### ISSUE THREAD

**Issue by zeroAska** [yuxng/SubCNN#5]
In Kitti test Step 5: we are going to "Copy the region proposals to `$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_*`"  

Here I'm confused which data to copy from? In `$ROOT/fast-rcnn/output/kitti`, there are four folders, `kitti_train`, `kitti_val`, `kitti_trainval`, and `kitti_test`.  

Then which folder should be copied to 
`$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_125/training`, 

to
`$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_227/training`,

and to 
`$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_227/testing`?

Thanks!

**Comment by zeroAska** [comment]
Another related questions is, from `$ROOT/fast-rcnn/data/KITTI`, I found that `trainval.txt` and `test.txt` only differ in the last few lines. In this case, in those testing scripts like `/experiments/scripts/kitti_test_googlenet_rcnn.sh`, why do we first train on `kitti_trainval` and then test on `kitti_test` ?

Thanks!

**Comment by yuxng** [comment]
$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_125/training contains region proposals from kitti_train and kitti_val

$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_227/training contains region proposals from kitti_trainval

$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_227/testing contains region proposals from kitti_test

**Comment by zhoutengteng** [comment]
“$ROOT/fast-rcnn/data/KITTI/region_proposals/RPN_125/training contains region proposals from kitti_train and kitti_val”， this means I simply copy from each folder into training folder?

**Comment by kamadforge** [comment]
The kitti_train, kitti_val, etc. will contain (after the training) caffemodel files. Should we copy those caffemodels to the region_proposals/RPN_* folders? Or, as it seems to me, the proposals are the text files which are in data?KITTI/voxel_exemplars folder. And should we copy those to the RPN_* folder? Please correct me if I am missing something.

**Comment by yuxng** [comment]
Yes, that's correct. Please copy all the region proposals to the training folder.
