### ISSUE TITLE
what does "ln -s $data_object_image_2 data_object_image_2" mean?

### ISSUE THREAD

**Issue by litingfeng** [yuxng/SubCNN#6]
when i downloaded the dataset, as it is a zip file, i just unzip it to a file and name it **data_object_image_2**. Is that right? 

How to link a file to a variable($data_object_image_2)?

 I'm a newbie. Thank you for your answer!

**Comment by MarkuzK** [comment]
Download the corresponding KITTI dataset -- http://www.cvlibs.net/download.php?file=data_object_image_2.zip ... extract it and then link to it

Markus
