### ISSUE TITLE
Kitti's testing speed

### ISSUE THREAD

**Issue by zeroAska** [yuxng/SubCNN#9]
What is the average testing speed on Kitti with Titan X GPU, for googlenet? I got around 12s per image, is it  natural? 

I'm not using CuDNN.

Thanks!

**Comment by yuxng** [comment]
For googlenet, I cannot use roi pooling layer since the convolution on an image cannot fit into GPU memory. Each region proposal is classified independently when using googlenet. I do not see big improve from VGG to googlenet on kitti. You could try VGG net which has roi pooling layer and is faster.

**Comment by zeroAska** [comment]
Thanks for the suggestion! If I'm understanding correctly, you're saying that with googlenet, each RoI is fed into the CNN one by one, while with VGG net, each image is fed into the CNN once, and there is no need for each RoI to go through the CNN individually (which is proposed by fast-rcnn). Is it correct?

**Comment by zeroAska** [comment]
@yuxng I tried to train on VGG, but I found that within the first 20 iteration, all loss become zero. Is it working correctly?

**Comment by zeroAska** [comment]
When I tried to train googlenet with kitti_val, this happens again, but Caffenet is fine.

**Comment by litingfeng** [comment]
@zeroAska hi, I was wondering if you could share your file `RPN_125/training`  with me, because when I use proposals in this file to draw on images, they appeared to be far from correct locations. I want to confirm if I trained correctly. 

Thank you!  my email: 420191163@qq.com
